CREATE TABLE `app_activity_share` (
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `ACTIVITY_NAME` varchar(64) NOT NULL COMMENT '分享主题名称',
   `ACTIVITY_TYPE` int(4) NOT NULL COMMENT '分享类型(1APP注册分享；2缴费成功分享)',
   `ACTIVITY_DESC` varchar(225) DEFAULT NULL COMMENT '分享描述',
   `SHARE_URL` varchar(100) NOT NULL COMMENT '分享地址',
   `SHARE_IMAGE` varchar(100) DEFAULT NULL COMMENT '分享配图',
   `IS_TIGER` int(4) DEFAULT '0' COMMENT '是否分享即刻触发',
   `IS_FROMUSER_TIGER` int(4) DEFAULT '0' COMMENT '是否允许来源用户触发',
   `GET_COUNT` int(4) DEFAULT '1' COMMENT '可领取次数',
   `VALIDITY` int(4) NOT NULL COMMENT '有效期 单位：天',
   `STATUS` int(4) DEFAULT '0' COMMENT '状态(1正常 0下线)',
   `DISPLAY_CONF` int(4) NOT NULL COMMENT '显示类型 1在APP上显示',
   `FLAG` varchar(16) NOT NULL DEFAULT '' COMMENT '操作标示 ADD：增加 UPDATE:修改 DELETE:删除',
   `CREATED_BY` varchar(36) NOT NULL COMMENT '创建人',
   `UPDATED_BY` varchar(36) DEFAULT NULL COMMENT '修改人',
   `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
   `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='分享活动消息表'

 CREATE TABLE `app_activity_share_getuser` (
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `USER_SHAREID` varchar(36) NOT NULL COMMENT '用户分享ID',
   `FROM_USER_ID` varchar(36) NOT NULL COMMENT '来源用户ID',
   `FROM_USER_ACCOUNT` varchar(32) DEFAULT NULL COMMENT '来源用户账号',
   `SOURCE` int(4) NOT NULL COMMENT '分享介质(微信好友，微信朋友圈，QQ等)',
   `TO_USERACCOUNT` varchar(32) NOT NULL COMMENT '领取用户号码',
   `IS_REG` int(4) NOT NULL COMMENT '是否注册',
   `REG_TIME` datetime DEFAULT NULL COMMENT '注册时间',
   `IS_HISTORY_USER` int(1) NOT NULL COMMENT '是否历史用户：1 是 0 不是',
   `IS_GETTICKET` int(4) DEFAULT '0' COMMENT '是否领券',
   `TICKET_NAME` varchar(64) DEFAULT NULL COMMENT '领取优惠券名称',
   `TICKET_CONF_ID` varchar(36) DEFAULT NULL COMMENT '领取优惠券id',
   `GETTICKET_TIME` datetime DEFAULT NULL COMMENT '领券时间',
   `FLAG` varchar(16) NOT NULL DEFAULT '' COMMENT '操作标示 ADD：增加 UPDATE:修改 DELETE:删除',
   `CREATED_BY` varchar(16) NOT NULL COMMENT '创建人',
   `UPDATED_BY` varchar(16) DEFAULT NULL COMMENT '修改人',
   `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
   `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `USER_SHAREID` (`USER_SHAREID`,`TO_USERACCOUNT`),
   UNIQUE KEY `UK_SHAREID_TOUSERACCOUNT` (`USER_SHAREID`,`TO_USERACCOUNT`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='用户分享领取表'

 CREATE TABLE `app_activity_share_user` (
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `ACTIVITY_SHARE_ID` varchar(64) NOT NULL COMMENT '分享活动ID',
   `USER_ID` varchar(64) NOT NULL COMMENT '用户ID',
   `USER_ACCOUNT` varchar(64) DEFAULT NULL COMMENT '用户账号',
   `SOURCE` int(4) NOT NULL COMMENT '分享介质(微信好友，微信朋友圈，QQ等)',
   `PARKRECORD_ID` varchar(64) DEFAULT NULL COMMENT '停车记录编号',
   `ORDER_NO` varchar(64) DEFAULT NULL COMMENT '订单编号',
   `STATUS` varchar(10) NOT NULL COMMENT '通知类型(200成功；100失败)',
   `FLAG` varchar(16) NOT NULL DEFAULT '' COMMENT '操作标示 ADD：增加 UPDATE:修改 DELETE:删除',
   `CREATED_BY` varchar(36) NOT NULL COMMENT '创建人',
   `UPDATED_BY` varchar(36) DEFAULT NULL COMMENT '修改人',
   `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
   `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='用户分享消息表'

 CREATE TABLE `app_resource_rel` (
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `RESOURCE_ID` varchar(36) NOT NULL COMMENT '资源表id',
   `CITY_CODE` int(10) NOT NULL COMMENT '城市编码',
   `RESOURCE_SIZE` varchar(10) DEFAULT NULL COMMENT '资源尺寸（大-large；中-middle；小-small）',
   `VERSION_CODE` varchar(16) NOT NULL COMMENT '版本号',
   `CREATED_BY` varchar(36) NOT NULL COMMENT '创建人',
   `UPDATED_BY` varchar(36) DEFAULT NULL COMMENT '修改人',
   `CREATE_TIME` datetime NOT NULL COMMENT '创建时间,默认SYSDATE',
   `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间,默认SYSDATE',
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='APP资源信息关联表'

 CREATE TABLE `app_stat_activity_effect` (
   `ID` varchar(36) NOT NULL COMMENT 'ID',
   `DAY_TIME` date NOT NULL COMMENT '日期',
   `CITY_CODE` int(8) NOT NULL COMMENT '城市编码',
   `AREA_CODE` int(8) NOT NULL COMMENT '区域编码',
   `ACTIVITY_NAME` varchar(64) NOT NULL COMMENT '活动名称',
   `ACTIVITY_ID` varchar(36) NOT NULL COMMENT '活动ID',
   `PUTLOG_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '发券总数',
   `USED_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '使用总数',
   `CUMULATIV_UNUSED_USER_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '累计未使用用户数',
   `CUMULATIVE_PARTICIPATE_USER_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '累计参与用户数',
   `CUMULATIVE_PAYFEE_ORDER_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '累计缴费订单数',
   `PAYFEE_USER_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '缴费用户数',
   `TICKETPAY_USER_COUNT` int(8) NOT NULL DEFAULT '0' COMMENT '券缴费用户数',
   `TICKET_MONEY_AMOUNT` int(8) NOT NULL DEFAULT '0' COMMENT '券总面额',
   `ACTUAL_DISCOUNT_AMOUNT` int(8) NOT NULL DEFAULT '0' COMMENT '实际抵扣总面额',
   `TICKET_DISCOUNT_SCALE` float NOT NULL DEFAULT '0' COMMENT '券抵扣金额占比',
   `REVENUE_GROWTH_RATE` float NOT NULL DEFAULT '0' COMMENT '收入同步增长率',
   `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='活动效果统计报表'

 /**app_resource表删除一些字段：*/
ALTER TABLE `app_resource` DROP COLUMN `city_code`;
ALTER TABLE `app_resource` DROP COLUMN ` VERSION_CODE`;
ALTER TABLE `app_resource` DROP COLUMN ` RESOURCE_SIZE`;

/**app_version修改VERSION_VALUE字段的类型为VARCHAR(16)*/
ALTER TABLE app_version MODIFY `VERSION_VALUE` VARCHAR(16) NULL COMMENT '版本值';
